
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: abdglobal/flaskapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        
---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - protocol: "TCP"
    port: 8080
    nodePort: 30136
    targetPort: 8080
